#!/bin/sh
# Generated by 'mxcli init', then adapted for this repo. COMMIT THIS FILE.
#
# Run by the Claude Code SessionStart hook to make a fresh (or reaped and
# re-cloned) session ready to work: obtain mxcli if the binary is missing, then
# cache MxBuild + the runtime and provision the local database.
#
# The mxcli binary is git-ignored (~88 MB), so after an idle reap it is NOT in
# the fresh clone — which is exactly why this script fetches it rather than
# skipping when it is absent.
#
# DELTA FROM THE STOCK SCRIPT: this project deliberately does NOT use the
# mendixlabs/mxcli nightly binary. It builds ako/mxcli from source, because the
# fork carries changes this project depends on. Override with:
#   MXCLI_REPO   git URL to build from   (default: https://github.com/ako/mxcli)
#   MXCLI_REF    branch/tag/commit       (default: main)
#   MXCLI_TAG    if set, skip the source build and download this mendixlabs
#                release tag instead (escape hatch when the build is broken)
set -e

MPR='ReplicationLab.mpr'
REPO="${MXCLI_REPO:-https://github.com/ako/mxcli}"
REF="${MXCLI_REF:-main}"
ANTLR_VERSION=4.13.2   # pinned by mdl/grammar/Makefile; a mismatch will not compile
SRC_DIR="${MXCLI_SRC_DIR:-/tmp/mxcli-src}"

build_from_source() {
  command -v go >/dev/null 2>&1 || { echo "go toolchain not found; cannot build mxcli from source." >&2; return 1; }
  command -v java >/dev/null 2>&1 || { echo "java not found; ANTLR codegen needs a JVM." >&2; return 1; }

  # The generated ANTLR parser is not committed, so 'go install' does not work
  # and the build needs the pinned generator on PATH as 'antlr4'.
  if ! command -v antlr4 >/dev/null 2>&1; then
    jar="/tmp/antlr-${ANTLR_VERSION}-complete.jar"
    [ -f "$jar" ] || curl -fsSL -o "$jar" "https://www.antlr.org/download/antlr-${ANTLR_VERSION}-complete.jar" || return 1
    mkdir -p /tmp/mxcli-bin
    printf '#!/bin/sh\nexec java -jar %s "$@"\n' "$jar" > /tmp/mxcli-bin/antlr4
    chmod +x /tmp/mxcli-bin/antlr4
    PATH="/tmp/mxcli-bin:$PATH"
    export PATH
  fi

  if [ -d "$SRC_DIR/.git" ]; then
    git -C "$SRC_DIR" fetch --depth 1 origin "$REF" && git -C "$SRC_DIR" checkout -f FETCH_HEAD
  else
    rm -rf "$SRC_DIR"
    git clone --depth 1 --branch "$REF" "$REPO" "$SRC_DIR" \
      || git clone --depth 1 "$REPO" "$SRC_DIR"
  fi

  ANTLR4_TOOLS_ANTLR_VERSION="$ANTLR_VERSION" make -C "$SRC_DIR" build
  cp "$SRC_DIR/bin/mxcli" ./mxcli
  chmod +x ./mxcli
  echo "Built mxcli from ${REPO}@$(git -C "$SRC_DIR" rev-parse --short HEAD)"
}

download_release() {
  os=$(uname -s | tr 'A-Z' 'a-z')
  case "$(uname -m)" in
    x86_64|amd64) arch=amd64 ;;
    arm64|aarch64) arch=arm64 ;;
    *) arch=$(uname -m) ;;
  esac
  url="https://github.com/mendixlabs/mxcli/releases/download/${MXCLI_TAG}/mxcli-${os}-${arch}"
  echo "Downloading mxcli ${MXCLI_TAG} for ${os}/${arch}..."
  curl -fsSL -o ./mxcli "$url" || return 1
  chmod +x ./mxcli
}

if [ ! -x ./mxcli ]; then
  if [ -n "$MXCLI_TAG" ]; then
    download_release || { echo "Could not download mxcli ${MXCLI_TAG}." >&2; exit 1; }
  else
    echo "mxcli not found — building ${REPO}@${REF} from source (a few minutes)..."
    build_from_source || {
      echo "Source build of ${REPO}@${REF} failed." >&2
      echo "Set MXCLI_TAG=vX.Y.Z (or nightly) to fall back to a mendixlabs release." >&2
      exit 1
    }
  fi
fi

# Keep .ai-context/skills/ in step with this binary. The skills are embedded in
# mxcli and written once by 'mxcli init', so upgrading the binary used to leave
# yesterday's guidance in place with no warning — and an agent reads stale
# guidance with the same confidence as current guidance. Quiet when already
# current; never fatal, since a skills refresh must not block the session.
./mxcli init --sync-skills . || true

exec ./mxcli run --local --setup --ensure-db -p "$MPR"
