// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package databasereplication.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import databasereplication.proxies.AdditionalJoins;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * Filters additionalJoins based on constraintInfo using trimmed string comparison and returns the first element of the list
 */
public class FilterAdditionalJoins extends UserAction<IMendixObject>
{
	/** @deprecated use com.mendix.utils.ListUtils.map(AdditionalJoinsList, com.mendix.systemwideinterfaces.core.IEntityProxy::getMendixObject) instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final java.util.List<IMendixObject> __AdditionalJoinsList;
	private final java.util.List<databasereplication.proxies.AdditionalJoins> AdditionalJoinsList;
	private final java.lang.String MatchString;

	public FilterAdditionalJoins(
		IContext context,
		java.util.List<IMendixObject> _additionalJoinsList,
		java.lang.String _matchString
	)
	{
		super(context);
		this.__AdditionalJoinsList = _additionalJoinsList;
		this.AdditionalJoinsList = java.util.Optional.ofNullable(_additionalJoinsList)
			.orElse(java.util.Collections.emptyList())
			.stream()
			.map(additionalJoinsListElement -> databasereplication.proxies.AdditionalJoins.initialize(getContext(), additionalJoinsListElement))
			.collect(java.util.stream.Collectors.toList());
		this.MatchString = _matchString;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		return this.AdditionalJoinsList.stream()
				.filter(join -> join.getConstraintsInfo().trim().equals(MatchString.trim()))
				.map(AdditionalJoins::getMendixObject)
				.findFirst().orElse(null);
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "FilterAdditionalJoins";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
